### PR TITLE
Parametrize script runner with `indirect=True`

### PR DESCRIPTION
**Pull request by jonchang**
This change is needed for pytest 5.4.0

c.f. https://github.com/pytest-dev/pytest/issues/5712

### CODE REVIEW

**Comment by kvas-it** [comment]
Hey! Thanks for the PR.

It seems that the test suite is broken because of changes to `virtualenv` so I will first need to fix that and then we can land this.

**Comment by kvas-it** [comment]
It seems that they have reverted the changes in the API ([changelog](https://docs.pytest.org/en/latest/changelog.html#pytest-5-4-1-2020-03-13), [ticket](https://github.com/pytest-dev/pytest/issues/6909)) so this change is no longer necessary.

Anyway, thanks for the PR -- it motivated me to fix the tests so they now work with the latest version of [virtualenv](https://virtualenv.pypa.io/en/latest/index.html) (#31).

I'm leaning towards merging this PR anyway since it doesn't have any downsides and makes it work with pytest 5.4.0. What do you think?

**Comment by jonchang** [comment]
Might as well; I don't think the `indirect` parameter is getting removed so it should help with 5.4.0 regardless.

**Comment by kvas-it** [comment]
Yeah, makes sense. Thank you for the PR!

**Pull request merged**
