### PR TITLE
Delay console script import to avoid overwriting global logging

### PR DESCRIPTION
**Pull request by NymanRobin**
Currently, in the inprocess use case, if the console script is in pkg_resources the global logging config is not saved. This happens because entry_points[0].load() triggers an import of the console script. This will load the global logging config before executing the console script. The _save_and_reset_logger() is called, causing it to overwrite the config. If we delay the import of the console script until execution, the global logging of the file will be active under execution. 

This PR delays the import of the console script. Which fixes the mentioned problem and makes the functionality symmetrical to the exec case.

### CODE REVIEW

**Comment by NymanRobin** [comment]
Any thoughts on this @kvas-it ?

**Comment by kvas-it** [comment]
Sorry for the delays with looking at this, times have been busy and I only got to it now.

Yes, this looks like a better approach to loading the entry points. I had a few formatting comments and I would like the added test to be in the same file as all other tests. It was quite a bit of changing, so I thought it would be easier just to send you a [pull request](https://github.com/NymanRobin/pytest-console-scripts/pull/1) -- if you like my edits, just merge it into your branch and then we'll merge this PR (with the added changes) into master.

Thank you for contributing!

**Comment by NymanRobin** [comment]
No problem! 
The changes looked good to me, thanks!

**Comment by kvas-it** [comment]
Thanks again. I can also make a new release if that would be useful for you, just let me know.

**Comment by NymanRobin** [comment]
Happy to contribute. A release would be appreciated.

**Comment by kvas-it** [comment]
[Done](https://pypi.org/project/pytest-console-scripts/1.2.1/)

**Pull request merged**
