### PR TITLE
Add Kyle Benesch to the list of maintainers

### PR DESCRIPTION
**Pull request by kvas-it**

### CODE REVIEW

**Comment by HexDecimal** [comment]
Is that the right format?  Could probably just move everything to `pyproject.toml`.

**Review by HexDecimal — APPROVED** [review]

**Comment by HexDecimal** [comment]
Random failures with Codecov.  I'm considering removing the error on failure. Apparently it might work smoother with the API token but I don't have access to it.  You should be able to go the Codecov settings to find `CODECOV_TOKEN=...` and add that as a secret key to this repo.
https://app.codecov.io/gh/kvas-it/pytest-console-scripts/settings

**Comment by HexDecimal** [comment]
Either that or remove the line `fail_ci_if_error: true` from the Codecov action on the workflow.

**Comment by HexDecimal** [comment]
For reference, the `pyproject.toml` would look like this:
```toml
[project]
name = "pytest-console-scripts"
authors = [
    {name = "Vasily Kuznetsov", email = "kvas.it@gmail.com"},
]
maintainers = [
    {name = "Vasily Kuznetsov", email = "kvas.it@gmail.com"},
    {name = "Kyle Benesch", email = "4b796c65+github@gmail.com"},
]
```

**Comment by kvas-it** [comment]
Thanks for the approval and advice about Codecov.

I added CODECOV_TOKEN to repository secrets. Now we just need to update `test.yml` to use it, right?

Regarding `pyproject.toml`: this structure looks a bit better as maintainer names are grouped together with the corresponding emails. Do you think it would be worthwhile to migrate some of the metadata into `pyproject.toml`?

**Comment by HexDecimal** [comment]
> I added CODECOV_TOKEN to repository secrets. Now we just need to update test.yml to use it, right?

Yes, it can be added like this:
```yml
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
```

> Do you think it would be worthwhile to migrate some of the metadata into pyproject.toml?

In my experience it's nice to move as much as possible to pyproject.toml.

**Comment by kvas-it** [comment]
I looked a bit into `pyproject.toml` and how it's used in `python-tcod` and it seems like it does simplify things. I'm gonna try moving most of `setup.py` metadata to it. It probably makes sense to make that a separate PR so I'll merge this one and open another one later.

**Pull request merged**
